import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import styles from "../styles/Home.module.css";
import React, { useState, useEffect } from "react";
import NonAnimatedGrid from "../components/NonAnimatedGrid";
import Technologies from "../components/Technologies";
import AnimatedGrid from "../components/AnimatedGrid";
import MainPage from "../components/MainPage";
import Footer from "../components/Footer";

export default function Home() {
  const [display, setDisplay] = useState(true);
  const [link, setLink] = useState("");

  return (
    <div className="flex flex-col justify-center items-center  sm:mt-24">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <MainPage showRight={true} />

      <NonAnimatedGrid />

      <div className="z-20 sm:w-1/2 overflow-hidden mt-12 relative">
        <div className="h-20">
          <div className="absolute space-y-7 ">
            <p className="text-4xl font-bold ">Technology we use</p>
            <p className="font-bold ">
              List of technologies we use and a short description
            </p>
          </div>
        </div>

        <Technologies />
      </div>

      <AnimatedGrid />
      <Footer />
    </div>
  );
}
